<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <AssemblyName>Serhat.Forge.CloudScript</AssemblyName>
    <RootNamespace>Serhat.Forge.CloudScript</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.8.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" OutputItemType="Analyzer" PrivateAssets="all" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.6.2" />
    <PackageReference Include="PlayFabAllSDK" Version="1.180.240426" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <None Update="host.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="local.settings.template.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
